### ISSUE TITLE
Network Piping

### ISSUE THREAD

**Issue by freddyC** [BrainJS/brain.js#113]
It would be cool to have a clean way built in to pipe the output from one network into the input of another network and allow the user to provide (if needed) a method for modifying the data before the pipe happens.

Here is what I am envisioning:
```js
// a network for finding individual hand written words on a scanned document
// an example input would be an array of the pixels of image
// an example output would be the same size as the input but each pixel would be either
// 1 for is part of word or 0 for is not part of word
var findNet = new FindNet (jsonOfFindNet);

// a network for splitting up hand written words into individual letters
// output would be similar to the one above
var splitNet = new SplitNet (jsonOfSplitNet);

// a network for determining the letter from handwriting 
var letterNet = new LetterNet (jsonOfSplitNet);

brain
  .run (findNet, imageOfDocument)
  .result ((input, output, ancestry) => {
    // Code to get the pixels of the input for groupings of output and return it as an array
    // that can be used in the next input
  })
  .pipeTo (splitNet)
  .result ((input, output, ancestry) => {
    // similar logic to above
  })
  .pipeTo (letterNet)
  .result ((input, output, ancestry) => {
        // User takes the given output then tracks the ancestry up the chain to determine
        // where on the page the letter was written, then prints the letter on a blank form. 
    });
```

I don't know if this works out perfectly but allowing some level of pipe-ability would allow complex systems to be created fairly simply.

**Comment by robertleeplummerjr** [comment]
v2.0.0 will have a means to do this. You can leave the output layer to be something exactly to be consumed as part of intermediate connection to another net.

**Comment by robertleeplummerjr** [comment]
Taking a step back and looking at this from a practical standpoint:  This can be accomplished using simply the run method, and different trained networks, _though not async_.

```js
const net1 = new brain.NeuralNetwork();
const net2 = new brain.NeuralNetwork();
const net3 = new brain.NeuralNetwork();

const output1 = net1.run([1,2,3]);
const output2 = net2.run(output1);
console.log(net3.run(output2));
```

However, if we reduce the visual complexity of a trained neural network to what it actually is we get:

```js
function net(input) {
  return output;
}
```

So quite literally a function that accepts one argument, and has an output, period.  It is hard to reduce that complexity because it is so simple.  Networks themselves have no idea they are actually networks, and they can easily be "bolted" onto others without difficulty.  We can add all types of function names, and abstract meaning, and make things more confusing, as is often the case in many frameworks, but I fail to see a reason for that here. In fact, if you'd like to wrap networks in promises so to inject into an already established async/promise architecture, something like this could be accomplished via:

```js
const net1 = new brain.NeuralNetwork();
const net2 = new brain.NeuralNetwork();
const net3 = new brain.NeuralNetwork();

run(net1, [1,2,3])
  .then(output => run(net2, output))
  .then(output => run(net3, output))
  .then((output) => {
    console.log(output);
  });

function run(net, input) {
  return new Promise((resolve) => {
    resolve(net.run(input));
  });
}
```
