### ISSUE TITLE
Training Generation

### ISSUE THREAD

**Issue by freddyC** [BrainJS/brain.js#114]
I think a lot of neural networks will be focused on vision.  Is it possible to generate training data.  For example could I take a smaller data set, then manipulate it and superimpose it onto a larger data set to get a reasonable result.

For example if I want to know if a chair is in a picture, could I take pictures of say, 500 different chairs in different angles, then print it over another 200 random pictures in different places and, in different sizes to create a huge data set?

For another example could I take a data set of 500 pictures that have chairs in them and then randomly duplicate the images but when I duplicate them either rotate or crop them in some way so that the image has changed.

Would this be biasing the network or hurt the training in a bad way?

If not would it be a good idea to include some sort of tool for doing this?  I doubt the tool would be in brain.js itself but a sister package or something that would easily take images and manipulate them, then convert them into useable input.

I guess I was just wondering about feedback on this before I try doing it myself lol.

**Comment by robertleeplummerjr** [comment]
>Would this be biasing the network or hurt the training in a bad way?

It seems this is a common practice, but you'd want to make sure you have enough data that isn't chairs, because if you didn't all you'd be training the net to do is to activate despite what is going into it.  If trained specifically and successfully to that of a chair it does lock the network into a specified route, which can be good or bad.

>If not would it be a good idea to include some sort of tool for doing this?

Imagenet seems to be the standard. Example of search for a chair: http://www.image-net.org/search?q=chair
I do think it'd be really helpful to have a library that you give results, and it prepares them into a consumable means, aka training data.

**Comment by mubaidr** [comment]
I am closing this issue, in case you need further help, please don't hesitate to re-open this issue or create a anew one.
