### ISSUE TITLE
how to customize activation function?

### ISSUE THREAD

**Issue by sayokagain** [BrainJS/brain.js#163]
now we have  4 activation function to use ( relu/leaky-relu/sigmoid/tanh)
but,...how to defined my activation function?

**Comment by robertleeplummerjr** [comment]
Bad news: With the `NeuralNetwork` class and its GPU sibling: `NeuralNetworkGPU`, this is challenging and so I won't really go into detail there.

Good news: With all other nets that we're working on this can easily be defined and is that way by design.  We don't want you to use just our layers, we want _any_ layers, _your_ layers.  Consider https://github.com/BrainJS/brain.js/blob/d9dc97746ffbc1d2071b82bcb7877880350da769/src/recurrent/lstm.js#L55 for example.  In that scenario you'd need to first setup a class though.  However, the news gets even better.  The new gpu powered neural net classes for both [feedforward](https://github.com/BrainJS/brain.js/blob/nn-gpu-layers/src/feed-forward.js) (which will shortly be released, and will be fully GPU powered, WebGL now, eventually OpenCL) and [recurrent](https://github.com/BrainJS/brain.js/blob/nn-gpu-layers/src/recurrent.js) (maybe two to three months till release?) allow you to do this at instantiation.  Here is an example partially borrowed from the [Roadmap](https://github.com/BrainJS/brain.js/wiki/Roadmap):

Simple version (tested and working):
```js
import { FeedForward, layer } from 'brain.js';
const { input, feedForward, output } = layer;
const net = new FeedForward({
  inputLayer: () => input({ width: 2 })
  hiddenLayers: [
    input => feedForward({ width: 3 }, input),
  ]
  outputLayer: input => output({ width: 1 }, input)
});
net.train([
  { input: [0, 0], output: [0] },
  { input: [0, 1], output: [1] },
  { input: [1, 0], output: [1] },
  { input: [1, 1], output: [0] }
]);
net.run([0, 0]); // [0]
net.run([0, 1]); // [1]
net.run([1, 0]); // [1]
net.run([1, 1]); // [0]
```

More explicit version:
```js
import { FeedForward, layer } from 'brain.js';
const { input, output, multiply, add, sigmoid } = layer;
const net = new FeedForward({
  inputLayer: () => input({ width: 2 })
  hiddenLayers: [
    (input) => {
      const width = 3;
      const weights = random({ name: 'weights', height: width, width: input.height });
      const biases = random({ name: 'biases', height: width });

      return sigmoid(
        add(
          multiply(
            weights,
            input
          ),
          biases
        )
      );
    }
  ]
  outputLayer: input => output({ width: 1 }, input)
});
net.train([
  { input: [0, 0], output: [0] },
  { input: [0, 1], output: [1] },
  { input: [1, 0], output: [1] },
  { input: [1, 1], output: [0] }
]);
net.run([0, 0]); // [0]
net.run([0, 1]); // [1]
net.run([1, 0]); // [1]
net.run([1, 1]); // [0]
```

There are a bunch of layer types to chose from: https://github.com/BrainJS/brain.js/tree/nn-gpu-layers/src/layer but you can just as well use your own, and have [tested for that exast scenario](https://github.com/BrainJS/brain.js/blob/nn-gpu-layers/test/feed-forward/unit.js) and is exactly what we feel is needed to be a serious library.

**No one library should dictate my or anyone else's creativity.**

Most of them are tested fairly well but some like convolution are still a little new and therefore may have some bugs, fyi.

Now keep this in mind: all of this will be GPU powered, super fast and the recurrent architecture mirrors this architecture nearly 1 to 1. 

Note: The new recurrent architecture is planned to depreciate the existing and initially recommended architecture.

**Comment by mubaidr** [comment]
I am closing this issue, in case you need further help, please don't hesitate to re-open this issue or create a anew one.
