### ISSUE TITLE
How to train a LSTM with word2vec?

### ISSUE THREAD

**Issue by laisooliveira** [BrainJS/brain.js#189]
I am building a chatbot with LSTM and want to train it with word2vec.
My word2vec has 50,000 words and 300 dimensions
Ex: habitat -1.3647801900 1.3738158900 0.2465990600 2.1891686900 0.6943694900 -2.6615395500 -2.2774395900 -0.7816810600 -2.0987477300 0.6752733000 0.2160997200 -2.5310149200 -0.0185884800 -0.1371951100 1.3544383000 -0.7495064100 -0.4740572900 0.4018277200 -0.3430224100 3.2751915500 2.1514051000 -0.6308519200 -0.0494690000 0.0152249800 0.7252819500 1.3675113900 -0.0091898100 -0.4859900800 -2.0218408100 2.1318612100 1.3574508400 0.0419076600 -0.5356218800 1.8430864800 1.8042033900 -1.7795616400 1.7969458100 -0.1753064500 1.2667079000 -0.0627308900 2.3582694500 0.3472277800 -1.7687833300 0.5584479600 -1.8952162300 -0.2527293900 0.2892596100 -0.5397638700 2.2907545600 0.3161168100 1.1883001300 0.2124780400 -0.6084006400 1.5877540100 -1.4548597300 0.6829087700 1.1628122300 -1.2890571400 -0.5202924000 -3.3226783300 1.6987195000 -1.2889652300 -1.0176618100 -0.8378086700 0.1067392400 -0.4657668500 -1.1100050200 -0.6819430000 1.5377532200 4.0890202500 -1.1155736400 0.0937739500 0.3992665100 -0.5781583800 -0.7426824600 -0.9722284100 -2.7184295700 2.2280111300 0.4557567200 0.3324293200 0.1180267900 -0.8125032800 -1.6899688200 0.8920158100 -0.9322571200 -1.2154240600 0.6924889100 2.3516814700 2.2570233300 0.4583316100 -0.8749604200 -0.2947839800 -0.3639003900 0.8426298500 -0.5391494600 -2.6293542400 -0.5343321600 -0.7278754700 -1.3837781000 -0.1214726400 3.2363083400 0.2855843600 0.8283597200 3.2165134000 5.1168689700 1.8635101300 0.6403925400 -0.0748401000 1.3461340700 1.4319884800 -0.5339683900 -3.8581769500 0.3334631000 -1.7722562600 1.6212118900 -0.9140905700 -2.7753143300 0.0369564900 1.0862236000 0.1020409900 1.5446523400 0.1595745500 1.8376504200 1.1515380100 -0.0980633800 0.0811093200 0.0267694200 0.2589508600 0.6539341800 1.9381942700 -0.3548978900 1.4094371800 -1.3229471400 0.2385898400 0.6828389200 2.0896759000 0.0594398700 0.4351980400 1.5370471500 1.5302144300 -0.1204863700 1.3607657000 1.7124875800 0.2046247600 0.2599546900 -1.8474105600 -1.4753555100 1.0440255400 -3.3957669700 1.0339361400 -0.8538480400 -0.5760051000 -1.1541284300 -2.0571205600 -2.3071939900 1.2198510200 1.1650621900 2.6165473500 1.6304169900 -1.0002026600 0.6577165700 -0.4267740000 2.4739301200 1.0608931800 -0.9494769000 0.8674579300 1.0640357700 -1.0086734300 -0.0127654700 -0.2298720300 0.3787490700 0.8874620200 1.3751823900 0.9126778200 -0.4775976800 2.9768061600 -1.2477245300 -2.2773942900 -4.0493512200 -1.8013587000 -0.9162495100 -1.6291481300 -1.1861761800 0.7705537700 0.5286152400 0.0126681900 -1.2365452100 -2.8135929100 -1.3852562900 0.7333450900 -1.7341587500 0.3457882100 -3.1126203500 0.2369786500 1.4351389400 1.5433987400 -1.4206522700 -0.0455815900 -1.7550355200 1.1177791400 -0.3880976400 1.2710317400 -2.7514941700 -1.1995364400 0.0352814700 0.6997430900 -1.6497966100 -0.9383609900 -0.5924424500 0.6684603100 -0.0437095200 -1.7479397100 3.7832143300 -2.9113018500 -0.5864983800 -1.3234059800 -2.4729344800 0.2311947500 -0.9925758200 -0.3781887600 -0.4839721000 -1.1160574000 1.1763583400 -0.8411796100 2.4462795300 -1.4976810200 1.0895487100 1.5365719800 -0.1850507900 -1.0345528100 0.0478989700 1.4634296900 0.0824523200 1.2698760000 0.6335535600 1.5134996200 -0.3667610300 0.9677723100 0.5201346900 -1.0649181600 -1.2869925500 0.0880658600 0.7587167000 0.3332204800 -0.0332824600 -3.3452012500 -0.0068436500 -0.8905732000 1.0225111200 -1.1799205500 -0.3684535900 0.9887036100 -3.8089571000 0.0325328200 -0.4620702900 1.9567893700 1.2629199000 2.3563311100 0.0145924500 -2.1898069400 0.9922846600 -0.5171598200 -1.0451976100 -0.3743359400 -1.7407307600 -0.0846587600 -0.5496798200 -0.8463670000 -0.4880480500 -1.5049734100 0.5707928500 1.7324128200 2.2713220100 0.3478857900 -1.6806889800 -0.3297997100 0.9927637000 0.6006448900 1.1168755300 -0.1322128200 -0.4416206200 -2.7686607800 -1.8041679900 -1.2512767300 2.4595532400 0.8618509800 -2.1972091200 1.9579937500 -0.3608679800 0.2267621600 -1.3405871400 -1.8404084400 -1.3168903600 1.0585155500 1.3245978400 -1.8002417100 -0.9839525200 -1.1119825800 -0.6331896800 0.9027283200

**Comment by robertleeplummerjr** [comment]
Can you share more of your infrastructure?

**Comment by josiahbryan** [comment]
@laisooliveira - curious as to exactly what you're asking. I'm looking at using `words2vec` as well, but wouldn't you just use the word vec as your input to your LSTM net, with the expected vec as the output?

**Comment by robertleeplummerjr** [comment]
>but wouldn't you just use the word vec as your input to your LSTM net

I think we're all learning here, we welcome the enthusiastic.

**Comment by chadmpdev** [comment]
@josiahbryan were you able to get your words2vec to work as your input to the LSTM? I'm in a similar boat.

**Comment by josiahbryan** [comment]
I haven't yet had a chance to revisit this, day job has kept me busy. I
plan to get back to it this weekend hopefully! I'll let you know!

**Comment by robertleeplummerjr** [comment]
I was able to refine our RNNTimeStep model to possibly assist with this sometimes in the next few days, fyi.


Added information here: https://gist.github.com/robertleeplummerjr/713a47d5fd63e8e189f8cf5cbc0649cd
And branch here: https://github.com/BrainJS/brain.js/compare/rnn-time-step-inputs?expand=1

**Comment by robertleeplummerjr** [comment]
Here is the current approach I was going to take with the branch mentioned above.

1. I have broken up the equation runners into being able to run by index (input of neuron) or by value (value directly into neuron).
2. On training: Having either side broken up, we can train, combining input (string) and vector (decimal) together.  
  * Think about mixing the ideology of both a RNN/LSTM _and_ a RNNTimeStep/LSTMTimeStep
3. On running: Because we know that inputs will be strings, and outputs... will be decimals(?) we have a fixed means of handling this scenario.


This brings me to asking this question:  @laisooliveira - Are you sure you want a LSTM + word2vec, when LSTM seems to handle words to words with some ease?

Example:
https://github.com/BrainJS/brain.js/blob/650c322a16b6c76b8adc374f3a9afb83ca6e50ee/examples/childrens-book.js

You can use strings like this with the LSTM:

```js
const lstm = new brain.recurrent.LSTM();
lstm.train([
  { input: 'input string', output: 'output string' }
]);
```

**Comment by robertleeplummerjr** [comment]
The reason I come to this question, to be more clear, is generally if we wanted to go one way or the other (words to vectors, or vectors to words), we'd be trying to pull values out of test to do something with them.  But if we are simply pulling text out to turn it into vectors, to turn that into text or something else, then the existing `brain.recurrent.LSTM` is probably what you want.

**Comment by robertleeplummerjr** [comment]
Another point, your 50,000 words will likely reduce in complexity if you so choose or need to use the existing `brain.recurrent.LSTM` because you'll be using mostly printable characters, rather than all 50k words.  While this does substantially lengthen the lstm equation, it may actually shorten iterations needed per step.

**Comment by seia-soto** [comment]
Also I am on same work with downloaded model from [here](http://vectors.nlpl.eu/repository/).

In my native language, and also determining swearing words, I think using Neural Net is better when getting a lot of exceptions. Because I want to process words as image (just this is word embedding). Making map of vectors of words can be done with other method, but it is not first time trying deep-learning things for me. Sorry about this.

Still I am not sure what to use TFJS between Brain.JS. However why I selected Brain.JS is I think TFJS was used to display result of Tensorflow models.

I am step using ``brain.recurrent.LSTM()`` to train and also I think I need vectors of word to get output.

I am trying like below.

```js
    const values = line.split(' ')

    const word = values[0]
    const vectors = values.shift()

    console.log('* Training word: ' + word)
    net.train(vectors)
```

**Comment by seia-soto** [comment]
I think this issue can be closed.

[Maybe got a way to learn?](https://github.com/Seia-Soto/BasicNeuralNetwork-VectorTraining)

**Comment by robertleeplummerjr** [comment]
word (string) to vec (number) isn't compatible with `LSTM`.  You may be able to do something with a `LSTMTimeStep`, but I'm not sure how I can be of help there.
