### ISSUE TITLE
Likely may need to go into a utility lib

### ISSUE THREAD

**Issue by robertleeplummerjr** [BrainJS/brain.js#2]
This is an issue raised by @nickpoorman.

I've been trying to think of a concept where I can make the likely method not attached to the neural network.  Currently it is:

``` javascript
var brain  = require('brain')
  , net    = new brain.NeuralNetwork
  ;
net.train([]);

var result = brain.likely([]);
```

Are you suggesting something like:

``` javascript
var brain  = require('brain')
  , likely = require('lib/likely')
  , net    = new brain.NeuralNetwork
  ;
net.train([]);

var result = likely(net, []);
```

?

**Comment by robertleeplummerjr** [comment]
Conversation started here: https://github.com/harthur/brain/issues/72#issuecomment-183728273

**Comment by robertleeplummerjr** [comment]
As is also mentioned in the comment above you mention: "convolutional neural networks are better suited for the example provided with that pull request", what type of neural network is this library?  Just curious.

**Comment by nickpoorman** [comment]
@robertleeplummerjr - You should be able to tell from the code that it's a simple single / muli-layer perceptron (feed forward with back propagation).

**Comment by robertleeplummerjr** [comment]
@nickpoorman Thanks for the explanation and pointers.  How does the proposed solution in the comment sit with you?

**Comment by nickpoorman** [comment]
Frankly, since y'all forked this repo you're free to do what you want. IMO your `likely` function is just a way of normalizing data (pre-processing) and really has nothing to do the artificial neural network.

For example, my [one-hot](https://github.com/nickpoorman/one-hot) library does something similar. It doesn't need to be a method on the instantiated "brain" object or even part of the repo, --you can always reference any good pre-processing libraries in your README if you so choose..

**Comment by robertleeplummerjr** [comment]
I completely agree.  Will be opening a PR soon to address this.  I really appreciate the feedback.

On a seperate note: one thing I love about this library so much is that it removes itself, giving you the raw neural net here: https://github.com/harthur-org/brain.js/blob/4389a60322d738cb679b6988a28c8332c50ebeba/lib/neuralnetwork.js#L387

I would be very interested in doing something with convolutional neural networks, perhaps something that could be done in a sister project.
