### ISSUE TITLE
Value1.concat is not a function error

### ISSUE THREAD

**Issue by techitesh** [BrainJS/brain.js#231]
Hi Guys I Just started Exploring brain.js and facing some issue 

```js
const brain                 = require('brain.js');
const faker                 = require('faker');
const co                    = require('co');



let payload = [];

const generateData = function () { 
    return new Promise((resolve,reject) => {
        const result = {input: {
            color:  faker.commerce.color(),
            price:  faker.commerce.price()
        },  output: { [faker.commerce.product()] : 1 } }
        return resolve(result);
    })
}

for (let index = 0; index < 100; index++) {
    payload.push(generateData());
}

Promise.all(payload).then(result => {
    console.log(result);
    var net = new brain.recurrent.LSTM();
    net.train(result)
    var output = net.run({ color: faker.commerce.color, price: faker.commerce.price });
    console.log(output);
})
```

Above is My Code where i am trying to Generate Some Fake eCommerce Data of Product with price and color attribute and output as a name of product 

But i am getting following Error

```
UnhandledPromiseRejectionWarning: TypeError: value1.concat is not a function
    at DataFormatter.toIndexesInputOutput (F:\demo\brain.js-demo\node_modules\brain.js\dist\utilities\data-formatter.js:103:40)
    at LSTM.formatDataIn (F:\demo\brain.js-demo\node_modules\brain.js\dist\recurrent\rnn.js:766:35)
    at LSTM.setupData (F:\demo\brain.js-demo\node_modules\brain.js\dist\recurrent\rnn.js:750:26)
    at LSTM.train (F:\demo\brain.js-demo\node_modules\brain.js\dist\recurrent\rnn.js:460:21)
    at Promise.all.then.result (F:\demo\brain.js-demo\server.js:26:9)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Function.Module.runMain (module.js:695:11)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
(node:12504) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch
block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:12504) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
Can Anyone Help me out Understanding What am i Doing Wrong in my code ???

**Comment by mubaidr** [comment]
This:
```js
brain.run
```

Should be 

```js
net.run
```

**Comment by techitesh** [comment]
@mubaidr I tried with net.run but still i am acing same issue

Here is My Sample Data that is getting generated from faker

```
[ 
    { input: { color: 'azure', price: '575.00' },​​​​​output: { Table: 1 } }​​​​​
]
```

**Comment by robertleeplummerjr** [comment]
I think your `result` variable looks like it needs to be changed from an object to an array with an object inside.

**Comment by mubaidr** [comment]
Can you please create a working fiddle with the same code? We will happily debug it.

**Comment by techitesh** [comment]
Here is a Stackblitz link please have a look 
https://stackblitz.com/edit/js-djf45m

**Comment by mubaidr** [comment]
Sorry for the delay, I am working on the provided example, thank you for that. 

On the first glance, I think the issue lies here: 
```js
return resolve(result);
```
You just need to call `resolve` should not return it. i.e. like this: 
```js
resolve(result)
```

**Comment by robertleeplummerjr** [comment]
Change this: `const result = {input: {...}}` to this: `const result = [{input: {...}}]`.

**Comment by robertleeplummerjr** [comment]
Nope, I'm wrong.

**Comment by techitesh** [comment]
Here is a New Stackblitz i have created 
https://stackblitz.com/edit/brain-js-demo

Lemme know if found any solutions

**Comment by mubaidr** [comment]
@techitesh Here is the fixed version: https://gist.github.com/mubaidr/145ddaef84280a137e0a4126ba8de9df

I have switched to RNN from LSTM because RNN is more suitable for simple mathematical data sets where LSTM is more suited to string/text data sets. 

But please note that network does not train well because data is not good (either repetitive or not conclusive enough). 

I am closing this issue, in case you need further help, please don't hesitate to re-open this issue or create a anew one.

**Comment by techitesh** [comment]
Thnx for Help

**Comment by mubaidr** [comment]
@techitesh  I am sorry, there was an issue the above gist, I have fixed it. More specifically: 
```js
parseInt(faker.internet.color().replace('#', ''), 16), //convert color to integer
```

**Comment by kmaher9** [comment]
To keep this issue alive, I'm experiencing the same issue also with an LSTM model. Reads in the content of 10 short files, into two outputs. After one or two iterations, sometimes immediately, I get the same error as OP. 

Gist of my code - https://gist.github.com/fauliath/d57660dfa78167b8acc63eb90e0d7974

My full error output is:

```
TypeError: value1.concat is not a function
    at DataFormatter.toIndexesInputOutput (Z:\Development\Javascript\NodeJS\Neural Networks\Brain.JS\002\node_modules\brain.js\dist\utilities\data-formatter.js:107:40)
    at LSTM.formatDataIn (Z:\Development\Javascript\NodeJS\Neural Networks\Brain.JS\002\node_modules\brain.js\dist\recurrent\rnn.js:767:35)
    at LSTM.setupData (Z:\Development\Javascript\NodeJS\Neural Networks\Brain.JS\002\node_modules\brain.js\dist\recurrent\rnn.js:751:26)
    at LSTM.train (Z:\Development\Javascript\NodeJS\Neural Networks\Brain.JS\002\node_modules\brain.js\dist\recurrent\rnn.js:460:21)
    at Object.<anonymous> (Z:\Development\Javascript\NodeJS\Neural Networks\Brain.JS\002\index.js:32:5)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
```

**Comment by robertleeplummerjr** [comment]
Clarity and direction for myself and the lib. 

The original use case is for this data shape, which (from my naive guess) was just converted directly to `brain.recurrent.LSTM`:

Overly simplified origin example:
```js
const trainingData = [
  {
    input: {
      color:  faker.commerce.color(),
      price:  faker.commerce.price()
    },
    output: { [faker.commerce.product()] : 1
  }
];
const net = new brain.NeuralNetwork();
net.train(trainingData);
```

The reason this was failing was specifically because `faker.commerce.color()` returns a string, which isn't a slam to `faker.commerce.color()`, but because color is essentially infinite (and more specifically because the net doesn't support it) we result in:
* in the existing version, training logs `NaN`
* in newer versions of brain.js this throws an error that training goes to `NaN`

Note: `faker.commerce.price()` also goes to string, but brain.js tries to handle this by casting to a decimal gracefully.

One could surmise that the `brain.recurrent.LSTM` class supports strings, and could thus just use that, and that _might_ work, but when one does change the software over, they arrive at an obtrusive `value1.concat is not a function` error, because `brain.recurrent.LSTM` by default has a nifty string encoder and only supports strings for inputs and outputs, with the option to extend however you like.  In short, the reason it fails is that the input `{ color: number, price: number }` simply doesn't have a `.concat()` method, and thus fails on preparing data.

BUT!  Taking a step back, consider your data shape:

```js
{
  input: {
    color:  number,
    price:  number
  },
  output: { [type] : number
}
```

There isn't really anything about this data shape that is recurrent.  Think of recurrence like memory of what is going on.  If all we are doing is classifying a color & price as an output, then the most appropriate network is likely the already used `brain.NeuralNetwork`, or more specifically, a FeedForward neural network.

However, what you may find advantageous is to _encode your data_ so that network can read it, or simply convert it appropriately.  This part has been left out of brain.js because, well, there are a lot of different types of data, and it can be read a lot of different ways.

One of the suggestions (added price casting as well for help) was to simply perform the following data conversions (ty @mubaidr & @techitesh):

Overly simplified suggested example:
```js
const trainingData = [
  {
    input: {
      color:  parseInt(faker.commerce.color().replace('#', ''), 16),
      price:  parseFloat(faker.commerce.price())
    },
    output: { [faker.commerce.product()] : 1
  }
];
const net = new brain.NeuralNetwork();
net.train(trainingData);
```

Unrelated note: Did you guys know the inverse of `parseInt('#509cd6'.replace('#', ''), 16)` is `(parseInt('#509cd6'.replace('#', ''), 16) >>> 0).toString(16)`?  Using bits directly in js is too fun.

And this works fairly well for running the net.  But training stops fairly quick:

<img width="370" alt="screen shot 2018-11-23 at 1 17 45 pm" src="https://user-images.githubusercontent.com/679099/48956679-5479e000-ef22-11e8-9110-9408dfb5e3bf.png">

Taking a much further step back, and for the sanity of those that may find this issue in the future: It is almost like the data is completely random (https://www.npmjs.com/package/faker), and that it is hard to classify things by _just random color and price_... :trollface:

Seriously, _really_ hard to do.  Likely impossible.  So short of building a lookup table, the net cannot learn this type of data without likely be over-fitting it.

If anyone else has this problem in the future, would you be so kind to include a sample of your training data?


Ty guys, sorry it took me a while to get to this one.

**Comment by fedorinov** [comment]
Today I start to train Fibi net not for input color data, (sorry bad
english) prinetstvie
And Fibi cant undestand it in whole. I need you help to finish this train,
please.


пт, 23 нояб. 2018 г., 21:45 Robert Plummer notifications@github.com:

**Comment by vli8** [comment]
Hey guys, I am having a similar issue on my project. For input I have an object of this format {string: int} and for output I have the same format {string: int}. The int (integer) being only 1 and 0s. 

`const express = require("express");
const morgan = require("morgan");
const path = require("path");
const PORT = 3500;
const seedDB = require("./db/seed");
const db = require("./db/database");
const brain = require("brain.js");
const { Wines } = require("./db/index");
const Sequelize = require("sequelize");
const Op = Sequelize.Op;
const network = new brain.recurrent.LSTM();

module.exports = network;

const app = express();
app.use(morgan("dev")); //middleware

app.use(express.json());
app.use(express.urlencoded({ extended: true }));
app.use(express.static(path.join(__dirname, "..", "public")));

app.use("/api", require("./api"));

app.use((err, req, res, next) => {
  console.log("ERROR: ", err);
  res.status(404);
});

const startServerConnectDB = async () => {
  await db.sync({ force: true });
  console.log("db synced, in the process of seeding the db...");
  await seedDB();
  await trainingData();
  app.listen(PORT, () => {
    console.log(`Listening on port ${PORT}`);
  });
};

const trainingData = async () => {
  const allWines = await Wines.findAll({
    where: {
      country: {
        [Op.ne]: null
      }
    }
  });

  const trainingData = [];
  for (let i = 0; i < 30; i++) {
    const descriptionOfWine = allWines[i].description; //string
    const countryWine = allWines[i].country;//string
    trainingData.push({
      input: { [descriptionOfWine]: 1 },
      output: { [countryWine]: 1 }
    });
  }
  await network.train(trainingData, { hiddenLayers: [3] });
  console.log("finished training Data!!!");
};
startServerConnectDB();
`

and this is where I run it 

`router.post("/winePrediction", async (req, res, next) => {
  try {
    console.log("BODY: ", req.body);
    console.log("network: ", network);
    const predictedCountry = network.run({ [req.body.description]: 1 }); //req.body.description is a string
    console.log("finished running: ");
    console.log(predictedCountry);
    res.send(predictedCountry);
  } catch (error) {
    console.log("error in wine prediction route", error);
  }
});`

The training data function is where I formatted the input output. Would anyone know what might be wrong? Thank you.
