### ISSUE TITLE
brain.js is taking too long to train my email data

### ISSUE THREAD

**Issue by hrwndr** [BrainJS/brain.js#308]
### brain.js is taking too long to train my email data
Brain.js is taking way too long to train my data which is some emails in a json file. This is my first day in ML and i would really appreciate the help. iterations are 200.

### My Code:
```
const brain = require('brain.js')
const data = require('./data.json')

const network = new brain.recurrent.LSTM()

let traningData = data.map(item => ({
  input: item.email,
  output: item.type
}))

network.train(traningData, {
  iterations: 200
})

console.log(
  network.run('Congratulations!! You won $10000')
)
```

**Comment by fedorinov** [comment]
Hello, please provide your json file. I will be glad to help you.


чт, 22 нояб. 2018 г., 15:59 Harwinder Singh notifications@github.com:

**Comment by hrwndr** [comment]
Thank you @fedorinov , here is my json file:
[data.json](https://bitbucket.org/hrwndr/brainjs-spamfilter/raw/fde342cff978b23cc187b0ea2f0955ec76fe625a/data.json)

**Comment by nandihno** [comment]
i ran the code and it seems that indeed it takes ages.
this happens with LSTM 
have you tried encoding the inputs and running on sigmoid?

so to encode the array of words
let encode = (arg) => { 
    let arr = arg.split('');
    return arr.map(ele => (ele.charCodeAt(0) / 255));
};

**Comment by hrwndr** [comment]
@nandihno 
Can u implement your encoding in my code?

**Comment by robertleeplummerjr** [comment]
If the encoding script is faster, then we need to look at the encoder, and ensure it is caching, because this should be the already in place means.

**Comment by fedorinov** [comment]
Fibi node want to sre how many percents ready to set working node . Nrt
need increasr this percent to hugo. We need train net with combination of
various types of nodes. I not understand many signs, but i see it. Please
if I do some errors plrase clear notify me and do new iteration. Add to
Fibi node  small nodes with excellent marks in skills. Fibi simple copy it
and students can copy more different tricks from Fibi. In real condition
this can save node from die.


пт, 23 нояб. 2018 г., 16:39 Robert Plummer notifications@github.com:

**Comment by robertleeplummerjr** [comment]
Taking a look here guys: https://jsfiddle.net/robertleeplummerjr/82vmsafb/7/

Ran a couple profilers:
<img width="1264" alt="screen shot 2018-11-23 at 2 17 47 pm" src="https://user-images.githubusercontent.com/679099/48958051-9870e300-ef2a-11e8-9944-a39679f937b4.png">

and 

<img width="1440" alt="screen shot 2018-11-23 at 2 18 22 pm" src="https://user-images.githubusercontent.com/679099/48958060-a7f02c00-ef2a-11e8-9914-0fd15387ef34.png">

And it turns out.... math in js on this scale is just slow (which is why I'm working on the GPU version).  and I'll keep digging for a few more minutes.  But rather than brute forcing this, perhaps we can simplify the problem.

Rethinking the strategy, what if we limit the input to words, rather than characters of an email?

I could only get it to print out: "ham", but if you tinker around with the settings, you may be able to change that.  It likely will need more data, and it might just be classifying them with length, but it is a start. 
https://jsfiddle.net/robertleeplummerjr/82vmsafb/98/

Probably some of my more ugly code, and will get much better when we have GPU.

Does this help?
