### ISSUE TITLE
Can you call net.train multiple times to add new data

### ISSUE THREAD

**Issue by jtsmedley** [BrainJS/brain.js#353]
![A GIF or MEME to give some spice of the internet](https://www.bing.com/th?id=OIP.CNvqYTaDHcLqX4xW1AsFlAEsDI&pid=Api)

## *What* is wrong?

Documentation Confusion

## *Where* does it happen?

Can you call net.train multiple times on the same net to add new learned data

## *How* do we replicate the issue?

I could write the code for the neural network, but I'm unsure how to test if it retains data.

## *How* important is this (1-5)?

4ish, but really great as we are using it on a hydraulic machine and would like to retrain with real time data.

## Expected behavior (i.e. solution)

I think you are so intelligent that you don't need intelligience, but no.  I think it would be nice if this is a feature, if not its not a deal breaker.

## Other Comments

**Comment by DanielMazurkiewicz** [comment]
You should be able to train NN again with new data only, but keep in mind that training will be performed on these new data only - the benefit will be that you'll just adjust your NN to new similar data instead of training from scratch. If your new data is something that adds up with old ones (you expect NN to behave well with situations presented in old and new data) then you should join these data before performing re-training.

> 4ish, but really great as we are using it on a hydraulic machine and would like to retrain with real time data.

This is very interesting use case, would be glad if you post here some more details (and pictures as well :-) )

**Comment by jtsmedley** [comment]
Thank You for this.  Solves my problem as I do expect historical data to be accurate.

![hg_001](https://user-images.githubusercontent.com/38006759/52150935-16dab700-2637-11e9-8157-ac7c4dd30695.jpg)

**Comment by jtsmedley** [comment]
Added image.
