### ISSUE TITLE
Suggestion requested: Is it a good idea to just add 0. on the beginning of the data

### ISSUE THREAD

**Issue by binary-person** [BrainJS/brain.js#358]
This is a quick question and I need someone's opinion on this. Is it a good idea to incorporate data in one string and adding 0. on the front of it? So if the data was for example, sentence encoding: 1925 1924 1392, into 0.192519241392. Would this work well?
I'm currently working on image classification and I need to incorporate rgb into one number. So would this work:
```
var r = getRed(pixelPosition);
var g = getGreen(pixelPosition);
var b = getBlue(pixelPosition);

train this: parseFloat('0.'+r+g+b;);
```
Thanks!

**Comment by robertleeplummerjr** [comment]
What are you trying to accomplish?  Encoding in that way will give the neuron that enough context to know what you are wanting it to learn.

**Comment by robertleeplummerjr** [comment]
Sorry, didn't see your clarification.  Add the three numbers, or pick one.

**Comment by binary-person** [comment]
Sorry for the misclarification. For a sentence, if I am encoding characters in a word, instead of inputting [0.5633, 0.2362, 0.1264] for the word 'hey' for example (h = 0.5633, e=0.2362, y=0.1264), I would just encode it like 0.**5633**2362**1264**. "Adding" them all together and putting a 0. on front of it. So I would instead train the neural network with [0.563323621264]. Would this be suggested? Does the neural network read what is in the decimals, or read the number as a whole?
Thanks for answering

**Comment by robertleeplummerjr** [comment]
>Sorry for the misclarification.

No worries.  I'm a bit frantic in the mid-day.

>I would just encode it like 0.**5633**2362**1264**

This simply won't work for the net to pick out meaning.  The reason is that you are:
1. delving into smaller and smaller detail, the further that you get from the decimal.
2. using 1 single float to represent what may add up differently.

You seem to need a recurrent neural network, like this:

```js
const net = new brain.recurrent.LSTM();
net.train(['How long would I have to train to run as fast as a train?', 'I used a pen to sketch the pig pen.', 'I usually just park in the park.']);
net.run('How long would I have to train') // -> ' to run as fast as a train?'
```

You can also use [different inputs and outputs with the LSTM](https://github.com/BrainJS/brain.js#for-training-with-rnn-lstm-and-gru).  Also, there is are [TimeStep](https://github.com/BrainJS/brain.js#for-training-with-rnntimestep-lstmtimestep-and-grutimestep) nets that can be used similarly if you'd like more control over values sent in and out.
