### ISSUE TITLE
training data formate

### ISSUE THREAD

**Issue by zhanghy-xyz** [BrainJS/brain.js#367]
Someone can tell me if brain. JS can support training data in the following format (input is the user's browsing behavior of each module on a page, output is the preference ranking of each module). Does brain.js have an application that is already online? I want to model it as an application. Looking forward to reply, thank you.
{
input: {
block_A: {move:0.4,click:4,count:10},
block_C: {move:0.6,click:7,count:8},
block_M: {move:0.9,click:3,count:4},
block_B: {move:0.4,click:7,count:16}
},
output: { block_C,block_B,block_A,block_M}
},{
input: {
block_A: {move:0.14,click:14,count:20},
block_C: {move:0.6,click:7,count:10},
block_M: {move:0.8,click:15,count:17},
block_B: {move:0.91,click:15,count:24}
},
output: { block_M,block_B,block_A,block_C}
}

**Comment by adajuly** [comment]
I also encountered the same problem, I look forward to the author reply.

**Comment by mubaidr** [comment]
There is a very similar example provided in the Read-me (color contrast demo): https://github.com/BrainJS/brain.js#data-format

This should work: 
```js
[
input: {
block_A: {move:0.4,click:4,count:10},
block_C: {move:0.6,click:7,count:8},
block_M: {move:0.9,click:3,count:4},
block_B: {move:0.4,click:7,count:16}
},
output: { block_C: 1,block_B: 0,block_A:0,block_M:0}
},{
input: {
block_A: {move:0.14,click:14,count:20},
block_C: {move:0.6,click:7,count:10},
block_M: {move:0.8,click:15,count:17},
block_B: {move:0.91,click:15,count:24}
},
output: { block_M:1,block_B:0,block_A:0,block_C:0}
]
```

**Comment by zhanghy-xyz** [comment]
> There is a very similar example provided in the Read-me (color contrast demo): https://github.com/BrainJS/brain.js#data-format
> 
> This should work:
> 
> ```js
> [
> input: {
> block_A: {move:0.4,click:4,count:10},
> block_C: {move:0.6,click:7,count:8},
> block_M: {move:0.9,click:3,count:4},
> block_B: {move:0.4,click:7,count:16}
> },
> output: { block_C: 1,block_B: 0,block_A:0,block_M:0}
> },{
> input: {
> block_A: {move:0.14,click:14,count:20},
> block_C: {move:0.6,click:7,count:10},
> block_M: {move:0.8,click:15,count:17},
> block_B: {move:0.91,click:15,count:24}
> },
> output: { block_M:1,block_B:0,block_A:0,block_C:0}
> ]
> ```

no ,Brain.js does not support two-dimensional data
var network = new brain.NeuralNetwork();
network.train([
  {
    input: {
      block_A: { move: 0.4, click: 4, count: 10 },
      block_C: { move: 0.6, click: 7, count: 8 },
      block_M: { move: 0.9, click: 3, count: 4 },
      block_B: { move: 0.4, click: 7, count: 16 },
    },
    output: { block_C: 1, block_B: 0, block_A: 0, block_M: 0 },
  },
  {
    input: {
      block_A: { move: 0.14, click: 14, count: 20 },
      block_C: { move: 0.6, click: 7, count: 10 },
      block_M: { move: 0.8, click: 15, count: 17 },
      block_B: { move: 0.91, click: 15, count: 24 },
    },
    output: { block_M: 1, block_B: 0, block_A: 0, block_C: 0 },
  },
]);

var result = network.run({
  block_A: { move: 0.14, click: 1, count: 2 },
  block_C: { move: 0.6, click: 6, count: 10 },
  block_M: { move: 0.8, click: 10, count: 17 },
  block_B: { move: 0.91, click: 11, count: 14 },
});
console.log(result);

//{ block_C: NaN, block_B: NaN, block_A: NaN, block_M: NaN }

**Comment by robertleeplummerjr** [comment]
>no ,Brain.js does not support two-dimensional data

This is actually incorrect, https://github.com/BrainJS/brain.js/blob/8455336e274277f571b236d98732b9f0890f5e63/test/recurrent/rnn-time-step.js#L588

The time step nets support this fine, however as your example does highlight, the `NeuralNetwork` class, is not, however, compatible with "two-dimensional data" as it stands.

@59337xyz Can you try `brain.recurrent.LSTMTimeStep` and see if that works for your needs?

**Comment by adajuly** [comment]
> 
> 
> > no ,Brain.js does not support two-dimensional data
> 
> This is actually incorrect,
> 
> [brain.js/test/recurrent/rnn-time-step.js](https://github.com/BrainJS/brain.js/blob/8455336e274277f571b236d98732b9f0890f5e63/test/recurrent/rnn-time-step.js#L588)
> 
> Line 588 in [8455336](/BrainJS/brain.js/commit/8455336e274277f571b236d98732b9f0890f5e63)
>  const trainingData = [ 
> 
> The time step nets support this fine, however as your example does highlight, the `NeuralNetwork` class, is not, however, compatible with "two-dimensional data" as it stands.
> 
> @59337xyz Can you try `brain.recurrent.LSTMTimeStep` and see if that works for your needs?
The requirement is to give a two-dimensional array containing several factors that affect this item. By comparing the factors between the arrays, one of the best recommended arrays is selected.


> 
> 
> > no ,Brain.js does not support two-dimensional data
> 
> This is actually incorrect,
> 
> [brain.js/test/recurrent/rnn-time-step.js](https://github.com/BrainJS/brain.js/blob/8455336e274277f571b236d98732b9f0890f5e63/test/recurrent/rnn-time-step.js#L588)
> 
> Line 588 in [8455336](/BrainJS/brain.js/commit/8455336e274277f571b236d98732b9f0890f5e63)
>  const trainingData = [ 
> 
> The time step nets support this fine, however as your example does highlight, the `NeuralNetwork` class, is not, however, compatible with "two-dimensional data" as it stands.
> 
> @59337xyz Can you try `brain.recurrent.LSTMTimeStep` and see if that works for your needs?

The requirement is to give a two-dimensional array containing several factors that affect this. By comparing the factors between the arrays, and choosing the best recommended array from it, can you help me give me an example?

**Comment by robertleeplummerjr** [comment]
Please don't take this as a "Please stay with brain.js because we need you!" but rather, just informing of state of handling this issue.  By all means, find the best tool for the job, if brain.js isn't the one you need, then find it.

We're actually building what you need in currently up to 3 dimensional data, perhaps more to come after that.  This includes the following shapes:

Note: The above list _is not_ a "Hey, wouldn't it be nice!" or "Wishful thinking", no.  It is _already supported_ by the underlying engine (gpu.js) and the v2 api for brain.js which is coming along nicely.

* Number (of course)
* Array (of course)
* Array2D
* Array3D
* Image
* ImageArray

And of course, the best for last (planning phase):
* Video
* N Dimension handling?  Interest pending

This is for WebGL AND node.  I'm trying to stay focused and get it done, and (if you follow a few issues on here) you'll see I've stated I'm 99% done, and I am.  Here is the issue that when closed will allow me to progress with GPU.js's v2 release: https://github.com/stackgl/headless-gl/issues/142.  I bring up GPU.js because brain.js's new architecture uses it.  I've literally been working on this issue this morning, and cannot get the textures to map, so I've written a webgl, webgl2, headless-gl, and google angle version of the same script in order to diagnose it.

Once done there, I can refocus priority on brain.js's v2 release, and **focus on this issue/feature as part of that priority**.

If you do find the above list enticing, and see an area you'd like to become active in or would like to know more, by all means GET ACTIVE.

**Comment by Eluvade** [comment]
> We're actually building what you need in currently up to 3 dimensional data, perhaps more to come after that. This includes the following shapes:

What's the status on the 2-dimensional arrays(or n-dimensional handling) for the NeuralNetwork class?

**Comment by robertleeplummerjr** [comment]
>Someone can tell me if brain. JS can support training data in the following format 

No, it cannot.

>What's the status on the 2-dimensional arrays(or n-dimensional handling) for the NeuralNetwork class?

It handles 1 dimensional.  `FeedForward` and `Recurrent` can handle 2 dimension, but they aren't yet fully released.
