### ISSUE TITLE
Flexible store

### ISSUE THREAD

**Issue by IonicaBizau** [BrainJS/brain.js#37]
Currently this works in memory. Would it be a good idea to extend this to work with any store (e.g. a database)? 

That means anyone can build a custom store object and expose the methods to `get` and `set` data.

**Comment by robertleeplummerjr** [comment]
This beacons to be asked: a GPU driven database store
![](https://media3.giphy.com/media/Sd4rgKxBUKPLy/giphy.gif)

**Comment by mubaidr** [comment]
^But why? care to share some specific use-case, please?

If you are talking about database for input data, then this does not fall under the specifications of this library. 
But otherwise as @robertleeplummerjr said, we need super fast solution to access data.

In both cases this is not under consideration for now.
