### ISSUE TITLE
old training data wont remain when i train with new data please help

### ISSUE THREAD

**Issue by ArsalanMaqsood** [BrainJS/brain.js#377]
const lstm = new brain.recurrent.LSTM();
lstm.fromJSON(myjson);
const result = lstm.train(trainingData, {
iterations: 15000,
log: details => console.log(details),
errorThresh: 0.011
});

const updatedjson = lstm.toJSON();

//, { flag: 'a+' }
fs.writeFile("results.json", JSON.stringify(updatedjson), function (err) {
if (err) throw err;
console.log('The "data to write" was appended to file!');
});

result.json file needs to have train data for new training and old training

how can i do this?

**Comment by mubaidr** [comment]
Please don't create duplicate threads as help is already being provided here: https://github.com/BrainJS/brain.js/issues/376#issuecomment-476207267

**Comment by CamK06** [comment]
> Please don't create duplicate threads as help is already being provided here: [#376 (comment)](https://github.com/BrainJS/brain.js/issues/376#issuecomment-476207267)

Briefly looking at #376 I found that it is not what he would Arsalan would like, what he would like to do is train a network, save it (which I think he has already done) and then be able to have a new dataset to train off of, load the network from the file that he created and ADD onto it instead of replacing its training.

 I also have had the same issue where I cannot, whatsoever get a network to add onto an old one.

**Comment by mubaidr** [comment]
Train network
Save json

Then later when you have new data: 

Create/Load network
Trian with old + new data
Save json
