### ISSUE TITLE
brain.recurrent.LSTM didn't works on Ubuntu

### ISSUE THREAD

**Issue by erfanium** [BrainJS/brain.js#426]
Hi, I'm trying to use barinJS on Ubuntu 18.04 with Node.js v10.
I use this code, it runs without any error but `net.train()` function takes the process to a blocking call. 
I will get no response.
```
const brain = require('brain.js');
const net = new brain.recurrent.LSTM();

net.train([
  'doe, a deer, a female deer',
  'ray, a drop of golden sun',
  'me, a name I call myself'
]);

const output = net.run('doe');

console.log('output:', output);


```

**Comment by mubaidr** [comment]
Please add `log: true` to train method to enable logging. https://github.com/BrainJS/brain.js#training-options

This will print some info for each training iteration.

**Comment by robertleeplummerjr** [comment]
They are working on release https://www.npmjs.com/package/brain.js/v/2.0.0-alpha.4, but there is something that is causing them to escalate to `Infinity` about 66% of the time.  I'm looking into it, and will have it solved ASAP.

**Comment by robertleeplummerjr** [comment]
Found it!  It was how `brain.recurrent.LSTM` and `brain.recurrent.GRU` were extending `brain.recurrnet.RNN`.  They were using the default, which is why they were [exploding or disappearing](https://en.wikipedia.org/wiki/Vanishing_gradient_problem).  Corrected and added tests so this never happens again [here](https://github.com/BrainJS/brain.js/commit/315a07315b13dec8f5fa2988e1358cac543bdfe6), released as https://www.npmjs.com/package/brain.js/v/2.0.0-alpha.5.  Good thing is that this resolves a number of issues across the board.  Ty for finding, and a pleasure doing (free) business with you!

**Comment by robertleeplummerjr** [comment]
Note that this includes `brain.recurrent.GRUTimeStep` & `brain.recurrent.LSTMTimeStep`.
