### ISSUE TITLE
Idea: Use Rollup instead of Parcel?

### ISSUE THREAD

**Issue by Symbitic** [BrainJS/brain.js#438]
## Other Comments

[Rollup](https://rollupjs.org/) is a bundler not unlike Parcel, but much more powerful (IMO). It can generate ES6 Modules (for webpack & environments that support them) and UMD files (which work in browsers and Node.js `require()`) with a single command.

So let's say we generate `brain.mjs` and `brain.js`. After that, use the following in `package.json`:
```js
"main": "./dist/brain.js",
"browser": "./dist/brain.min.js",
"module": "./dist/brain.mjs"
```
Webpack, Rollup, and Parcel will automatically use `brain.mjs`. Node.js will automatically use `brain.js` (unless experimental modules is active). Web browsers can keep using `brain.min.js`.

Rollup almost always produces smaller bundles than Webpack or Parcel. And bower could be removed.

I'm willing to work on porting to Rollup by myself; I just want to know if the maintainers are willing to use it.

**Comment by mubaidr** [comment]
I do use. Rollup.js and I like it. Currently we so support all npm fields except esm support.  Imho, configuring rollup builds are also easier.
So yeah, go ahead.

**Comment by robertleeplummerjr** [comment]
It might be a good idea to asses gpu.js as well, so that we get as small of a build as possible.

**Comment by robertleeplummerjr** [comment]
I do want to use some caution with regard to building node files.  We are currently developing with node and there is something beautiful about changing tons of stuff, and clicking a play button and it just work.

There are, however, caution(s) to be had when working with transpilers such as GPU.js, or transpiler outputs, via babel, *which are disgusting* (yes, Babel guys, I hope you are reading), to other transpilers, like GPU.js, *which are beautiful*, (_tl;dr_ shameless plug...

### ...but I've got the [unit tests to prove it](https://github.com/gpujs/gpu.js/tree/develop/test/internal)!
![](https://media3.giphy.com/media/3o6UBdd79rm7vxtOSs/giphy.gif)

But, in their defense, we're working with a subset of javascript rather than... ALL of it, but I will not take back the rant! _end tl;dr_)

...that turn javascript into GPU code.  There are side effects at times, many of which are handled in GPU.js, BUT we can only go so far, as the garbage that most transpilers output simply violate the laws of all things sacred... and that can be detected and ran on the GPU.

That being said, although es6 is nice (specifically imports and exports) if that is all we're (and we just removed them) working towards, I'm not sold, as it just waists time.

Our current build system needs to be evaluated as well, as there may be side effects with it, it is just that transpilers specifically, and specifically the ones in babel, are the ones that have given me the most trouble.

**Comment by robertleeplummerjr** [comment]
Also, I do want to clarify, the people who work on Babel do some amazing stuff, and I'm in no way saying their work is bad, I'm just saying that their transpilation output generally violates beautiful code, and rules of what will run on a GPU from javascript.

**Comment by mubaidr** [comment]
You have raised very good point indeed. We can take some very good points from current build scripts of `gpu.js`. (Like that how it build for browser skipping the `gl` dependency)

On the other hand, I am in favor of babel as it is a good tool to make your code compatible with all of the current generation browsers. The issue is with the configuration, we have to skip or avoid `gpu.js` parsing through `babel` and all our problems should solve. (I think so?)

So all in all this is how things should work in my humble opinion:
1. don't parse `gpu.js` code through babel to avoid code conversion issues
2. maybe: upgrade `gpu.js` build scripts to `roll.js` as well for similar configuration between `brain.js` and `gpu.js`
3. skip `gl` dependency from both build scripts
4. for `node.js` target we have to choices that will effect how we develop current code
    4.1. develop the script using latest technologies, which will aid in development and off-course could help in better code management. Then we build it for `node.js` using `gl` as external dependency and skipping `gpu.js` from babel transpiling. **This will give much better `node.js` versions support and better development support but will require building for each release, not much hassle since we can use github actions for that. (we are also building for browsers though)** 
    4.2. Develop the script using features fully supported in `node.js` LTS release. This will require us to make sure code we are developing is tested in same `node.js` as expected and does not use any latest feature not supported by LTS. 
5. Add github actions for build release to make sure we have  build scripts updated to github repo and npm with tags. 



@Symbitic for information please

**Comment by Symbitic** [comment]
I'll see what I can do. And I'll try to make it as incremental as possible, so as to avoid breaking things.
Not sure Babel really needs to come into the picture at this point. That can be added later, AFTER Rollup is working. Rollups only job is to bundle multiple input files into an output file, in one of several formats (ESM, CJS, UMD, etc).

I'm not sure how long this will take me. I'll need to take a look at GPU.js first before I can really get started on this. But I've got several ideas. I'm fairly confident I can get this working.

**Comment by mubaidr** [comment]
Please check this config as a starting point: https://github.com/mubaidr/Javascript-Barcode-Reader/blob/master/rollup.config.js

**Comment by Symbitic** [comment]
I got started working on GPU.js first.
First version is working! Check out my work at https://github.com/Symbitic/gpu.js

I want several people to review it before I actually create a merge request.

Some of my changes:
* I had to HEAVILY refactor almost every file to use ES6 Modules instead of CommonJS. Speaking of which:
* Circular dependencies are an abomination from Hell! I had to refactor a lot of files to remove it. I also had to remove the two functions in `utils.js` that used the `GPU` class. IT JUST COULDNT BE DONE! Besides, it didn't look like anyone or anything was actually using them. Plenty of other refactors were necessary.
* `HeadlessGL` is not included in browser builds. It was just too much effort, it resulted in big bloaty files, and it can't be used anyway. I might add a stub class for the browser build though.
* I wasn't able to get js-beautify working yet. Will you please consider using prettier or something else instead?

Not all tests are working yet. I think most of the errors have to do with `Array1D`, `Array2D` and so forth. Feel free to run the tests and make suggestions.

**Comment by mubaidr** [comment]
@Symbitic Any progress here?

**Comment by Symbitic** [comment]
I actually made quite a bit a little while ago, but all the commits since then make it a little difficult to update and merge. I will try soon, if I have time.
