### ISSUE TITLE
Run doesn't holds training output format.

### ISSUE THREAD

**Issue by mnini** [BrainJS/brain.js#503]
If I get array as output from LSTM in training, the result of net.run is just string...

```
    net.train(test)
    console.log(typeof test[0].output) // object // Array
    console.log(typeof net.run(test[0].input)) // string
```

**Comment by robertleeplummerjr** [comment]
Can you please post a jsfiddle or similar to reproduce?

**Comment by robertleeplummerjr** [comment]
This is expected behavior.  Reproduced here: https://observablehq.com/@robertleeplummerjr/brain-js-issue-503-reproduced

The RNN or LSTM (or GRU) use representative values, converted to strings and so strings are the expected output.  You can write your own data translator like this: https://github.com/BrainJS/brain.js/blob/342f055af18ff65e337bd110956fd82cd01de6ea/src/recurrent/rnn.js#L784, which is what is used by default, or if you have no need and would like to feed values directly in, you can use a timestep: https://github.com/BrainJS/brain.js#for-training-with-rnntimestep-lstmtimestep-and-grutimestep, which is like a non-fancy RNN/LSTM.
