### ISSUE TITLE
Attention layer, convolutional and ability to combine layers

### ISSUE THREAD

**Issue by kmaximur** [BrainJS/brain.js#547]
Hi! It would be cool to add Attention layer, Convolutional and ability to combine layers (CNN+LSTM, LSTM+Attention+CNN, etc). 
Are you planning to do it?

**Comment by robertleeplummerjr** [comment]
I hadn't planned on it personally, but the idea was that new layers could be added fairly easily with the new format for layers: https://github.com/BrainJS/brain.js/tree/master/src/layer

Do you have an implementation or documentation that could be used to plan it?  Would you like to build it?

**Comment by ChocolateLoverRaj** [comment]
@robertleeplummerjr I saw this in the v2 roadmap:
```js
new FeedForward({
  inputLayer: () => { /* return an instantiated layer here */ }
  hiddenLayers: [
    (input) => { /* return an instantiated layer here */ },
    /* more layers? by all means... */
    /* `input` here is the output from the previous layer */
  ]
  outputLayer: (input) => { /* return an instantiated layer here */ }
});
```
And I'm excited to create nueral networks with convolution layers. Is there anything I can help with to speed up the progress for using `input => layer` functions in `hiddenLayers`?

**Comment by robertleeplummerjr** [comment]
The backpropagation function `compare` in the `Pool` layer needs finished.  It may be one of the last things that needs done for it all to work: https://github.com/BrainJS/brain.js/blob/6a5aefd9f9271774580b47d697c934b1a2b840d2/src/layer/pool.ts#L304

I'm currently looking at https://github.com/BrainJS/brain.js/issues/701#issuecomment-1009002413, but if you'd like to put some attention there, it'd be much appreciated.

**Comment by ChocolateLoverRaj** [comment]
@robertleeplummerjr I'm new to programming neural networks. What is the `compare` method supposed to do? I noticed only some classes which extend `Layer` have a `compare` method.

**Comment by ChocolateLoverRaj** [comment]
@robertleeplummerjr I can try changing the `NeuralNetwork` constructor to use mixed layers
https://github.com/BrainJS/brain.js/blob/6a5aefd9f9271774580b47d697c934b1a2b840d2/src/neural-network.ts#L158
https://github.com/BrainJS/brain.js/blob/6a5aefd9f9271774580b47d697c934b1a2b840d2/src/neural-network.ts#L205

**Comment by robertleeplummerjr** [comment]
I'm not sure what a mixed layers are.  The `compare` method is where backpropagation happens.  It is the inverse of the forward propagation `predict` method. For reference you could look at frameworks such as tensorflow.js.  What separates brain.js GPU abilities from tensorflow.js is that tensorflow.js tends to have one matrix mutation at a time, where with brain.js we tend to stack them if at all possible, shortening the amount of GPU setup which substantially speeds things up, in theory.  However with backpropagation it can be slightly confusing, because of the amount of ray-casting that must be done.  All of which are somewhat advanced concepts, but simple once understood.

**Comment by ChocolateLoverRaj** [comment]
> I'm not sure what a mixed layers are.

I meant `ability to combine layers`

**Comment by robertleeplummerjr** [comment]
Oh yea, we call those "compound layers".

**Comment by robertleeplummerjr** [comment]
Getting back to the core question here:
>Are you planning to do it?

Yes.
