### ISSUE TITLE
GPU doesn't work at all

### ISSUE THREAD

**Issue by andrew-medvedev** [BrainJS/brain.js#716]
## _What_ is wrong?

Training isn't working in `gpu` mode. I have big dataset(around 160k lines, ~27 inputs and 1 output) and I run 2 same trainings - with cpu and gpu
```
var net = new brain.NeuralNetworkGPU({
    hiddenLayers: [layer1, layer2],
    activation: 'sigmoid',
    errorThresh: 0.0001,  // error threshold to reach before completion
    iterations: iter,   // maximum training iterations
    log: log => {
        console.log(log);
        console.log(` ~ PASSED from last iter: ${prettyms(_.now() - _tn)} ; from beginning: ${prettyms(_.now() - _t0)}`);
        _tn = _.now();
    },
    mode: 'gpu',
    logPeriod: 1,       // number of iterations between logging
    learningRate: 0.3    // learning rate
});
```
and
```
var net = new brain.NeuralNetwork({
    hiddenLayers: [layer1, layer2],
    activation: 'sigmoid',
    errorThresh: 0.0001,  // error threshold to reach before completion
    iterations: iter,   // maximum training iterations
    log: log => {
        console.log(log);
        console.log(` ~ PASSED from last iter: ${prettyms(_.now() - _tn)} ; from beginning: ${prettyms(_.now() - _t0)}`);
        _tn = _.now();
    },
    mode: 'cpu',
    logPeriod: 1,       // number of iterations between logging
    learningRate: 0.3    // learning rate
});
```
and thats what I see: ![](https://i.gyazo.com/1c73ff50175c9fc9848c5cbb72f7af96.png)

any alternatives to brain.js?

## _Where_ does it happen?

In the a NeuralNetwork when trying to train a net in node.js on my mac

## _How_ do we replicate the issue?

- Get mac m1
- generate big dataset
- run training in gpu mode

## Expected behavior (i.e. solution)

Training at the left at least works also 100000 times faster

## _How_ important is this (1-5)?

5

**Comment by robertleeplummerjr** [comment]
What data are you training on?

**Comment by andrew-medvedev** [comment]
on this [newItemsHintsPoints2-1.dataset.normalized.txt.zip](https://github.com/BrainJS/brain.js/files/6669870/newItemsHintsPoints2-1.dataset.normalized.txt.zip)

**Comment by EduApps-CDG** [comment]
same here

**Comment by robertleeplummerjr** [comment]
The problem you are experiencing is that you are using various sized training data for a class (`NeuralNetwork` and `NeuralNetworkGPU`) that accepts a fixed number of inputs or outputs based on how it is originally setup or detected from training data.  This has been a long standing issue because the NeuralNetwork class wouldn't validate or throw, though it really should have.

I took some time this week to address this issue and go ahead and provide these early validation and throws in both the `train` and `run` of both classes `NeuralNetwork` and `NeuralNetworkGPU` to indicate the misuse of their functionality.

The pull request: https://github.com/BrainJS/brain.js/pull/781
The unit tests:
* https://github.com/BrainJS/brain.js/pull/781/files#diff-f7791ae311aab9efb9fb62a4803504e1368630283c277c46efa1a6fc469846a2R8
* https://github.com/BrainJS/brain.js/pull/781/files#diff-279643acb105095021a03450f3eb5f923fd8a31bd8bd997524e19fa73b9f5934R4
* The release: https://www.npmjs.com/package/brain.js/v/2.0.0-beta.12

I hope this helps.
