### ISSUE TITLE
LSTMTimeStep with inputSize != outputSize?

### ISSUE THREAD

**Issue by labidus** [BrainJS/brain.js#723]
## Summary

It seam impossible with LSTMTimeStep to have an outputSize != inputSize?

I would like 6 inputs with 2 outputs, if it's possible how you feed the training data? I try everything and it seam not possible.

### Basic example

I would imagine if I could use this but this not work...

this.net.train([{
input: [1,2,3,4,5,6],
output: [1,2]
},
{
input: [1,2,3,4,5,6],
output: [1,2]
},
])

I can only feed with array

[
[1,2,3,4,5,6],
[1,2,3,4,5,6],
]
without output value... I suppose the output value is the next value (but is the input also) but I need 2 output size not 6

### Motivation

I want to predict [LOW, HIGH] of crypto candlestick and the INPUT is [OPEN, HIGH, LOW, CLOSE, VOLUME, TRADES]

But I don't care about predicting the other values since it's garbage data and predict 2 values is faster to train compare to 6!

Thank you!

**Comment by robertleeplummerjr** [comment]
It has been a bit tricky to fit these different sizes into a LSTMTimeStep.   Once options would be to do something like this:
```ts
this.net.train([
  {
    input: [[1,2],[3,4],[5,6]],
    output: [[1,2]]
  },
  {
    input: [[1,2],[3,4],[5,6]],
    output: [[1,2]]
  },
]);
```

Would this work for you?  Here is a link to a working version: https://observablehq.com/@200128059da6b2a3/brain-js-issue-723-solution

**Comment by niembro64** [comment]
If one has n inputs and m outputs, how does one configure, train, and run an LSTMTimeStep?

I only just realized that my LSTMTimeStep has likley not been using all elements of my input array. 

---------------

After some testing I believe that this model is acting similar to the normal brain.js LSTM. With the below configuration I was expecting all 14 of the output to be the same number, because the hidden layer of "one" squeezes the data. But, I am seeing the items in the output array changing slightly. 

export const myNetInputLength = 14;
export const myNetHiddenLengths = [10, 1];
export const myNetOutputLength = 14;

export const myLSTMTimeStepConfig = {
  inputSize: myNetInputLength,
  hiddenLayers: myNetHiddenLengths,
  outputSize: myNetOutputLength,
};

Output: 
output Float32Array(14) [
  0.6509473323822021,
  0.6546584367752075,
  0.6463162899017334,
  0.6509334444999695,
  0.6444850564002991,
  0.6511456966400146,
  0.6507893204689026,
  0.6524162292480469,
  0.6570031642913818,
  0.653138279914856,
  0.6572321653366089,
  0.645645022392273,
  0.6551721096038818,
  0.6522011756896973
]
output Float32Array(14) [
  0.4858695864677429,
  0.4868605136871338,
  0.4847656190395355,
  0.48590022325515747,
  0.484081894159317,
  0.4859100580215454,
  0.4859526753425598,
  0.48627960681915283,
  0.48734208941459656,
  0.48654231429100037,
  0.4874507188796997,
  0.48445016145706177,
  0.48690441250801086,
  0.48629865050315857
]
