### ISSUE TITLE
returns NaN everytime !!

### ISSUE THREAD

**Issue by elhadjx** [BrainJS/brain.js#866]
![A GIF or MEME to give some spice of the internet](url)

## _What_ is wrong?
it is returning NaN after running for couple of minutes! on both NeuralNetwork() and NeuralNetworkGPU() 
also training network takes really long 

## _How_ do we replicate the issue?
I don't know if it's because of my Dataset or something else but here's it

data sample: 
`input: [
    17163.9, 16440.8, 17215.5, 16433.2,
     348.22,     4.4,   723.5,   952.2,
      738.3,   707.4,   651.6,   562.7,
        540,    76.6,    63.4,     175,
      153.3,   144.2,   118.6,    43.1,
          3,     5.7,     4.6,     4.7,
        4.9,     4.5,     1.9
  ],
  output: [
      16972, 17093.6,
    16884.5, 17112.6,
    16966.5, 17089.3,
    16835.2
  ]`

code:
`
const net = new brain.NeuralNetwork();

net.train(trainData);

const prediction = net.run([
  17112.3,
  17225.6,
  17288.6,
  17082.1,
  274.42,
  -0.66,
  -113.4,
  277.1,
  23,
  145.8,
  -0.3,
  227.8,
  18.7,
  12.8,
  30.1,
  28.2,
  5.7,
  77.3,
  105.1,
  47.4,
  -3,
  0.8,
  -1.4,
  0.2,
  -2,
  0.6,
  -1.4]);
console.log(prediction); 
`

**Comment by JDStephens31** [comment]
Do you have an output? Data samples need an input and output as far as i know. (Ex. input: [1,0,1,0], output: 0)

**Comment by purplnay** [comment]
You can try normalizing your data to be numbers between 0 and 1 as specified in the [data format](https://github.com/BrainJS/brain.js#data-format) documentation.

Regarding the training taking long, this may be normal depending on the size of the dataset or the complexity of your network's structure.
If you havn't yet, you can set the `log` [training option](https://github.com/BrainJS/brain.js#training-options) to `true`, by default it will print the training process into the console on every 10th iteration, starting at the first iteration (`iterations: 0`). You can make it log more often by changing the `logPeriod` option to a lower interation interval (eg 5 instead of 10).

I hope this helps!

**Comment by elhadjx** [comment]
this helps alot! thank you!
